### PR TITLE
Updated weather icons and BTC icon

### PR DESCRIPTION
**Pull request by NSD4rKn3SS**
Made the weather icons and the BTC/USD icon a bit more fancy via using more colors.
(Did this edit a few months back, but completely forgot about offering it to the community)

### CODE REVIEW

**Comment by 0ooYoo0** [comment]
I would prefer to keep the plugins as they are 😃.
Therefore i will close your PR without merging, but I will add your icons to a separate folder with a small description in the documentation how to replace the built-in plugin icons.
What do you think?

**Comment by NSD4rKn3SS** [comment]
Its perfectly fine with me :) thanks for including my creations!

**Comment by BlueAndi** [comment]
@NSD4rKn3SS Meanwhile Pixelix supports larger displays too. Would you mind to create additional a 16x16 icon in gif format?
Köszönöm!

**Comment by NSD4rKn3SS** [comment]
Hey, sure thing!
I'll try and come up with something nice. :)

Animated GIFs are supported now too?
If so, is there a frame limit?

(P.s. I gotta get my matrix up and running again, my 5v PSU died a year ago or so, and i didn't had the time to search for a proper replacement)

Igazán nincs mit, örömmel segítek!

**Comment by nhjschulz** [comment]
@ Igazán 

 

I made a view attempts on 16x16 animated OW icons some time ago.  Maybe they can serve as some starting point.

I used piskel for drawing (https://www.piskelapp.com/)

 

 

Best regards,

Norbert

 

Von: NSD4rKn3SS ***@***.***> 
Gesendet: Dienstag, 1. Oktober 2024 06:23
An: BlueAndi/Pixelix ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [BlueAndi/Pixelix] Updated weather icons and BTC icon (PR #80)

 

Hey, sure thing!
I'll try and come up with something nice. :)

Animated GIFs are supported now too?
If so, is there a frame limit?

(P.s. I gotta get my matrix up and running again, my 5v PSU died a year ago or so, and i didn't had the time to search for a proper replacement)

Igazán nincs mit, örömmel segítek!

**Comment by NSD4rKn3SS** [comment]
@nhjschulz Thanks for the recommendation.
A friend of mine already told me about another software, https://github.com/aseprite/aseprite
But i haven't managed to compile it for myself, so i've stuck with GIMP for the time being.

I've actually made some progress on the icons, animated most of the 8x8 pack i've made before, just to get the hang of it again.
When i'm finished i'll tackle the 16x16 version.

**Pull request closed without merging**
