### PR TITLE
compiled version

### PR DESCRIPTION
**Pull request by 1danielsan**
Hello, is it possible to have a compiled basic version .bin file? 
Thank you very much

### CODE REVIEW

**Comment by BlueAndi** [comment]
Just a note, you opened a pull request, but I guess you wanted to open an issue, right?
Or do you mean a .bin version from the development branch?

I think its possible in the future to provide binary versions of all targets. The CI must be updated to provide them automatically.

**Comment by BlueAndi** [comment]
See #72

**Comment by 1danielsan** [comment]
Sorry, but I don't understand if right now there is (and where) a .bin version ready to use of the main branch. Sorry but I am new of github and it is not so easy to navigate it!

Is it also available the .stl for 3d printing the case? (cannot find it!)
Thank you very much.

**Comment by BlueAndi** [comment]
No, till now there is no binary (.bin) provided, but with the next upcoming version 5.0.0 see #72. I updated the CI to automatically provide them (hopefully, because I couldn't test it yet) in case I release a new version. I can not promise a release date for v5.0.0 but we are in stabilization phase right now.

For the case see my answer in #66
I don't own a 3d printer by myself, therefore a friend printed the parts for me. See in the #66 the links to thingiverse.

**Comment by 0ooYoo0** [comment]
Please have a look at the [partititionTable](https://github.com/BlueAndi/esp-rgb-led-matrix/tree/master/partitionTables) to find the respective addresses.

**Comment by 1danielsan** [comment]
Thank you, 
So... Just to be sure...
Main program should go in 0x10000 and spiff in 0x2B0000?  Is it correct?

**Comment by 0ooYoo0** [comment]
Yes correct.

**Pull request closed without merging**
