### PR TITLE
BTCQuote plugin clean and proper submission

### PR DESCRIPTION
**Pull request by flcu**
Plugin to get BTC -> USD Quote from coindesk.com

### CODE REVIEW

**Review by BlueAndi — COMMENTED** [review]
Just some minor things. Commit them and your pull-request will autom. be updated.
After that we merge it.

**Comment by BlueAndi** [comment]
BTW You commit locally with a different user, therefore your github account user is not shown. No problem for now, so there is no need to setup another pull-request. But in the future it will help later to see who was responsible for the commits.

**Comment by flcu** [comment]
thanks and done.

I'm not sure, I understand the issue with the username. I've set my local git username to my github username:
```
PS C:\Users\flavio\github\esp-rgb-led-matrix> git config --global user.name       
flcu
```
And the same for the email. Is there anything else I need to set?

**Comment by BlueAndi** [comment]
The email address is important.

**Comment by flcu** [comment]
Ah, right, there was a typo in the setting - thank you. Should be fixed.

**Review by BlueAndi — APPROVED** [review]
Ok.

**Pull request merged**
